import { StagingEvent, ImportBatch } from '@/types/staging';

// ステージングイベントのモックデータ
export const mockStagingEvents: StagingEvent[] = [
  {
    id: 'stg-1',
    canonicalUrl: '/events/stg-1',
    officialUrl: 'https://example.com/spring-festival',
    updatedAt: '2026-01-05',
    title: '春のお花見フェスティバル 🌸',
    summary: '桜が満開の公園で、家族みんなで楽しめるお花見イベントです。',
    startAt: '2026-03-20T10:00:00+09:00',
    endAt: '2026-03-20T16:00:00+09:00',
    area: { slug: 'ueno', name: '上野' },
    venue: { name: '上野恩賜公園', address: '東京都台東区上野公園' },
    age: { min: 0, label: '全年齢' },
    price: { text: '無料' },
    categories: ['アウトドア', '公園'],
    status: 'Staging',
    reservation: { required: false },
    importBatchId: 'batch-001',
    importedAt: '2026-01-05T09:00:00+09:00',
    validationErrors: [],
    validationWarnings: [],
    xEligible: false,
    lineEligible: true,
  },
  {
    id: 'stg-2',
    canonicalUrl: '/events/stg-2',
    officialUrl: 'https://example.com/robot-workshop',
    updatedAt: '2026-01-05',
    title: 'ロボット工作ワークショップ 🤖',
    summary: '初めてでも大丈夫！簡単なロボットを組み立てて動かしてみよう。',
    startAt: '2026-02-15T13:00:00+09:00',
    endAt: '2026-02-15T16:00:00+09:00',
    area: { slug: 'akihabara', name: '秋葉原' },
    venue: { name: 'テクノセンター', address: '東京都千代田区外神田' },
    age: { min: 6, max: 12, label: '小学生' },
    price: { min: 2000, text: '2,000円（材料費込み）' },
    categories: ['工作', '科学'],
    status: 'Staging',
    reservation: { required: true, method: 'web', reservationUrl: 'https://example.com/robot-reserve' },
    importBatchId: 'batch-001',
    importedAt: '2026-01-05T09:00:00+09:00',
    validationErrors: [],
    validationWarnings: [{ field: 'categories', message: 'カテゴリを確認してください', code: 'MISSING_CATEGORIES' }],
    xEligible: true,
    lineEligible: true,
  },
  {
    id: 'stg-3',
    canonicalUrl: '/events/stg-3',
    officialUrl: '',
    updatedAt: '2026-01-05',
    title: '動物ふれあい広場',
    summary: 'かわいい動物たちと触れ合える特別イベントです。',
    area: { slug: 'yokohama', name: '横浜' },
    venue: { name: '横浜ズーラシア' },
    age: { min: 3, label: '3歳〜' },
    price: { text: '入園料のみ' },
    categories: ['動物園', '体験'],
    status: 'Staging',
    reservation: { required: false },
    importBatchId: 'batch-002',
    importedAt: '2026-01-05T10:30:00+09:00',
    validationErrors: [{ field: 'officialUrl', message: '公式URLが必要です', code: 'INVALID_URL' }],
    validationWarnings: [{ field: 'startAt', message: '開始日時が設定されていません', code: 'MISSING_START_DATE' }],
    xEligible: false,
    lineEligible: true,
  },
  {
    id: 'stg-4',
    canonicalUrl: '/events/stg-4',
    officialUrl: 'https://example.com/cooking-class',
    updatedAt: '2026-01-04',
    title: '親子クッキング教室 👨‍🍳',
    summary: '親子で一緒に簡単なお菓子作りを楽しめます。',
    startAt: '2026-02-01T10:00:00+09:00',
    endAt: '2026-02-01T12:00:00+09:00',
    area: { slug: 'shibuya', name: '渋谷' },
    venue: { name: 'クッキングスタジオ渋谷', address: '東京都渋谷区...' },
    age: { min: 4, max: 10, label: '4歳〜10歳' },
    price: { min: 3000, text: '3,000円（親子ペア）' },
    categories: ['ワークショップ', '体験'],
    status: 'Staging',
    reservation: { required: true, method: 'web', reservationUrl: 'https://example.com/cooking-reserve', deadlineAt: '2026-01-25' },
    importBatchId: 'batch-002',
    importedAt: '2026-01-05T10:30:00+09:00',
    validationErrors: [],
    validationWarnings: [],
    duplicateCandidates: [
      { eventId: '4', title: 'お正月飾りを作ろう！工作教室 🎍', matchReason: 'SIMILAR_TITLE_AND_DATE', matchScore: 0.65 },
    ],
    xEligible: true,
    lineEligible: true,
  },
];

// インポートバッチのモックデータ
export const mockImportBatches: ImportBatch[] = [
  {
    id: 'batch-001',
    fileName: '2026年1月イベント_第1弾.csv',
    importedAt: '2026-01-05T09:00:00+09:00',
    importedBy: 'admin@example.com',
    totalRows: 2,
    successCount: 2,
    errorCount: 0,
    warningCount: 1,
    status: 'Completed',
  },
  {
    id: 'batch-002',
    fileName: '2026年2月イベント.csv',
    importedAt: '2026-01-05T10:30:00+09:00',
    importedBy: 'admin@example.com',
    totalRows: 2,
    successCount: 1,
    errorCount: 1,
    warningCount: 1,
    status: 'PartialSuccess',
  },
];

// エリア一覧（追加分）
export const opsAreas = [
  { slug: 'shinagawa', name: '品川' },
  { slug: 'shibuya', name: '渋谷' },
  { slug: 'shinjuku', name: '新宿' },
  { slug: 'yokohama', name: '横浜' },
  { slug: 'setagaya', name: '世田谷' },
  { slug: 'nerima', name: '練馬' },
  { slug: 'ueno', name: '上野' },
  { slug: 'akihabara', name: '秋葉原' },
  { slug: 'ikebukuro', name: '池袋' },
  { slug: 'odaiba', name: 'お台場' },
];
