import { Event } from '@/types/event';

// モックデータ（開発用）
export const mockEvents: Event[] = [
  {
    id: '1',
    canonicalUrl: '/events/1',
    officialUrl: 'https://example.com/ichigo-gari',
    updatedAt: '2026-01-01',
    title: 'いちご狩り体験 🍓',
    summary: '旬のいちごを自分で収穫して、その場で食べられる体験イベントです。お子様から大人まで楽しめます。',
    startAt: '2026-01-11T10:00:00+09:00',
    endAt: '2026-01-11T15:00:00+09:00',
    area: { slug: 'yokohama', name: '横浜' },
    venue: { name: '○○農園', address: '神奈川県横浜市...' },
    age: { min: 3, label: '3歳〜' },
    price: { min: 1500, max: 2000, text: '1,500円〜2,000円' },
    categories: ['体験', '自然'],
    status: 'Published',
    publishedAt: '2025-12-20',
    reservation: { required: true, method: 'web', reservationUrl: 'https://example.com/reserve' },
    imageUrl: '/images/event1.jpg',
  },
  {
    id: '2',
    canonicalUrl: '/events/2',
    officialUrl: 'https://example.com/science-museum',
    updatedAt: '2026-01-02',
    title: '親子で楽しむ科学実験教室 🔬',
    summary: '身近な材料を使った科学実験を通じて、理科の楽しさを体験できます。',
    startAt: '2026-01-12T13:00:00+09:00',
    endAt: '2026-01-12T16:00:00+09:00',
    area: { slug: 'shinagawa', name: '品川' },
    venue: { name: '品川科学館', address: '東京都品川区...' },
    age: { min: 5, max: 12, label: '5歳〜小学生' },
    price: { min: 0, text: '無料' },
    categories: ['学習', '科学'],
    status: 'Published',
    publishedAt: '2025-12-22',
    reservation: { required: true, method: 'lottery' },
    imageUrl: '/images/event2.jpg',
  },
  {
    id: '3',
    canonicalUrl: '/events/3',
    officialUrl: 'https://example.com/park-event',
    updatedAt: '2025-12-28',
    title: '冬の公園でアスレチック体験 🏃',
    summary: '広い公園でアスレチック遊具を使って思いっきり体を動かそう！',
    startAt: '2026-01-11T09:00:00+09:00',
    endAt: '2026-01-11T17:00:00+09:00',
    area: { slug: 'setagaya', name: '世田谷' },
    venue: { name: '世田谷公園', address: '東京都世田谷区...' },
    age: { min: 0, label: '0歳〜' },
    price: { text: '無料' },
    categories: ['アウトドア', '公園'],
    status: 'Published',
    publishedAt: '2025-12-25',
    reservation: { required: false },
    imageUrl: '/images/event3.jpg',
  },
  {
    id: '4',
    canonicalUrl: '/events/4',
    officialUrl: 'https://example.com/craft-workshop',
    updatedAt: '2026-01-03',
    title: 'お正月飾りを作ろう！工作教室 🎍',
    summary: '親子で一緒にお正月飾りを作る工作ワークショップです。',
    startAt: '2026-01-05T10:00:00+09:00',
    endAt: '2026-01-05T12:00:00+09:00',
    area: { slug: 'shibuya', name: '渋谷' },
    venue: { name: '渋谷区民センター', address: '東京都渋谷区...' },
    age: { min: 4, max: 10, label: '4歳〜10歳' },
    price: { min: 500, text: '500円（材料費込み）' },
    categories: ['工作', 'ワークショップ'],
    status: 'Published',
    publishedAt: '2025-12-30',
    reservation: { required: true, method: 'web', reservationUrl: 'https://example.com/reserve-craft' },
    imageUrl: '/images/event4.jpg',
  },
  {
    id: '5',
    canonicalUrl: '/events/5',
    officialUrl: 'https://example.com/aquarium',
    updatedAt: '2026-01-01',
    title: '水族館ナイトツアー 🐟',
    summary: '夜の水族館を特別に見学できるツアーです。昼間とは違う生き物たちの姿を観察しよう。',
    startAt: '2026-01-18T18:00:00+09:00',
    endAt: '2026-01-18T20:00:00+09:00',
    area: { slug: 'shinagawa', name: '品川' },
    venue: { name: 'アクアパーク品川', address: '東京都港区...' },
    age: { min: 3, label: '3歳〜' },
    price: { min: 2500, text: '2,500円' },
    categories: ['水族館', '体験'],
    status: 'Published',
    publishedAt: '2025-12-28',
    reservation: { required: true, method: 'web', reservationUrl: 'https://example.com/aquarium-night' },
    imageUrl: '/images/event5.jpg',
  },
  {
    id: '6',
    canonicalUrl: '/events/6',
    officialUrl: 'https://example.com/zoo-event',
    updatedAt: '2025-12-29',
    title: '動物園でお仕事体験 🦁',
    summary: '動物園の飼育員さんのお仕事を体験できる特別プログラムです。',
    startAt: '2026-01-12T09:30:00+09:00',
    endAt: '2026-01-12T12:00:00+09:00',
    area: { slug: 'nerima', name: '練馬' },
    venue: { name: '練馬動物園', address: '東京都練馬区...' },
    age: { min: 6, max: 12, label: '小学生' },
    price: { min: 1000, text: '1,000円' },
    categories: ['動物園', '体験'],
    status: 'Published',
    publishedAt: '2025-12-26',
    reservation: { required: true, method: 'lottery', deadlineAt: '2026-01-05' },
    imageUrl: '/images/event6.jpg',
  },
];

// エリア一覧
export const areas = [
  { slug: 'shinagawa', name: '品川' },
  { slug: 'shibuya', name: '渋谷' },
  { slug: 'shinjuku', name: '新宿' },
  { slug: 'yokohama', name: '横浜' },
  { slug: 'setagaya', name: '世田谷' },
  { slug: 'nerima', name: '練馬' },
];

// カテゴリ一覧
export const categories = [
  '体験',
  '自然',
  '学習',
  '科学',
  'アウトドア',
  '公園',
  '工作',
  'ワークショップ',
  '水族館',
  '動物園',
  'スポーツ',
  '音楽',
];

// 年齢レンジ
export const ageRanges = [
  { value: '0-2', label: '0〜2歳' },
  { value: '3-5', label: '3〜5歳' },
  { value: '6-12', label: '小学生' },
];
